### ISSUE TITLE
Add app id and profile type properties to ProvisioningProfile

### ISSUE THREAD

**Issue by adig** [rayh/xcoder#10]
This is more of a feature request. 
It would be useful that the ProvisioningProfile object to have appid property (application-identifier from the mobileprovision file) and a way to know if it's an AdHoc or an AppStore profile. (I think this only applies to iOS provisioning profiles only).
A way to tell which one is it is by checking for the ProvisionedDevices key (the AppStore profile doesn't have this key). 

Thanks

**Comment by rayh** [comment]
Hi,

This sounds easy enough to do, but I may not get a chance to do it
until next week.  Ideally, we would need to create example files for
the different sorts of mobile provisions you can get, without tying it
to a real app/account.

Ray

On 15 February 2012 02:20, Adrian Geana
reply@reply.github.com
wrote:

> This is more of a feature request.
> It would be useful that the ProvisioningProfile object to have appid property (application-identifier from the mobileprovision file) and a way to know if it's an AdHoc or an AppStore profile. (I think this only applies to iOS provisioning profiles only).
> A way to tell which one is it is by checking for the ProvisionedDevices key (the AppStore profile doesn't have this key).
> 
> Thanks
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rayh/xcoder/issues/10

## 

## Ray Hilton

a: 13/243 Collins Street, Melbourne VIC 3000
m: 0430 484 708
w: http://rayh.com.au

**Comment by rayh** [comment]
Added support for getting device ids and type from the profile.
