### ISSUE TITLE
OBJROOT and SYMROOT should be configurable

### ISSUE THREAD

**Issue by blakewatters** [rayh/xcoder#29]
I have some static library dependencies that build relative to the build products (into ../../Headers actually). Because of the default behavior of forcing OBJROOT and SYMROOT = /build/, this results in a  Headers/ dir being populated at the top of my project. This is not desirable. Should provide accessors on the builder object to enable overloading the objroot and symroot.

**Comment by rayh** [comment]
I think the pull request covered the issue you raised here, so closing this issue
