### ISSUE TITLE
A failed test quit the ruby process?

### ISSUE THREAD

**Issue by siuying** [rayh/xcoder#39]
To run a test on XCoder, i use following call:

```
builder.test
```

But, when the test completed with failure, the VM quit as per https://github.com/rayh/xcoder/commit/e7e9dc486566f188331846a183124839e0e4ab96

It would be helpful if we could use the test result:

```
result = builder.test
if result.failed?
  logger.warn "something bad happened!" 
else
  logger.info "everything is fine"
end
```

Maybe we can add the number of tests started/passed/failed into the result object too.

What do you think?

**Comment by rayh** [comment]
This is now implemented, please take a look and let me know if this makes sense
