### ISSUE TITLE
OCUnit Report Refactoring Results in NoMethodError

### ISSUE THREAD

**Issue by blakewatters** [rayh/xcoder#41]
The recent refactoring of the Report class has left an error case when testing beings. The issue is in the following code starting at line 20 within ocunit_parser.rb:

``` ruby
        def <<(piped_row)
          case piped_row.force_encoding("UTF-8")

            when /Test Suite '(\S+)'.*started at\s+(.*)/
              name = $1
              time = Time.parse($2)
              if name=~/\//
                @report.start
              else
                @report.add_suite name, time
              end
```

The issue is that when the regular expression matches and `@report.start` is invoked, there is no corresponding method. I have put together a basic spec and pull request that fixes it.

**Comment by rayh** [comment]
Fixed by pull request #42
