### ISSUE TITLE
Failure to Parse Root Node Crashes

### ISSUE THREAD

**Issue by blakewatters** [rayh/xcoder#44]
So I recently switched between branches and wound up with a directory structure named Something.xcodeproj, but it contained no actual project data. This results a nasty crash when it tries to access the root node of the project, which was implicitly loaded via a directory scan of the pwd. It would probably make sense to rescue this exemption and log a warning that there is a malformed project file rather than crashing hard. I had to put debuggers and logging statements into the gem source to figure out wtf was going on.

**Comment by burtlo** [comment]
Great suggestion. I will add that post haste.

**Comment by burtlo** [comment]
Alright I think I have this licked. When a file does not exist or is malformed it raises a generic: `Failed to correctly parse the project file FILEPATH`
