### ISSUE TITLE
supporting cocoapods with xcoder

### ISSUE THREAD

**Issue by yosit** [rayh/xcoder#51]
Hi,
first thanks for the superb work you have done.

I just started using xcoder and everything worked like a breeze until I started using cocoapods.
Now it doesn't compile and complains:
 ld: library not found for -lPods

Tried working through the workspace and get the project through it and it didn't work either,
Tried to build the pods project first and then my app and it broker earlier.

Is there a nice way to make these work together?

**Comment by blakewatters** [comment]
Hi @yosit -

I have had success building an Xcode Workspace with CocoaPods. You definitely need to go through the Workspace to reach the Target and if you are trying to execute Unit Tests, you'll need to add an explicit Scheme for the unit test targets. Here's the configuration from the @RestKit unit tests Rakefile:

``` ruby
namespace :test do
  task :kill_simulator do
    system(%q{killall -m -KILL "iPhone Simulator"})
  end

  namespace :logic do
    desc "Run the logic tests for iOS"
    task :ios => :kill_simulator do
      config = Xcode.workspace(:RestKit).scheme(:RestKitTests)
      builder = config.builder
      build_dir = File.dirname(config.parent.workspace_root) + '/Build'
      builder.symroot = build_dir + '/Products'
      builder.objroot = build_dir
        builder.test(:sdk => 'iphonesimulator')
    end

    desc "Run the logic tests for OS X"
    task :osx do
      config = Xcode.workspace(:RestKit).scheme(:RestKitFrameworkTests)
      builder = config.builder
      build_dir = File.dirname(config.parent.workspace_root) + '/Build'
      builder.symroot = build_dir + '/Products'
      builder.objroot = build_dir
        builder.test(:sdk => 'macosx')
    end
  end    

  desc "Run the unit tests for iOS and OS X"
  task :logic => ['logic:ios', 'logic:osx']
end
```

Hope this helps.

**Comment by yosit** [comment]
Thanks Blake.
This my script:
Xcode.find_projects.each {|p| puts p.name }
scheme = Xcode.workspace(workspace).scheme(scheme)

builder = scheme.builder
builder.profile = provisioning_profile    # This will remove old profiles
and install the profile
builder.identity = provisioning_identity       # The name of the identity
to use to sign the IPA (optional)
builder.clean
builder.build :sdk => :iphoneos
builder.package

I can't get it to build.
Any idea whats wrong?

On Mon, Jan 28, 2013 at 9:17 PM, Blake Watters notifications@github.comwrote:

> Hi @yosit https://github.com/yosit -
> 
> I have had success building an Xcode Workspace with CocoaPods. You
> definitely need to go through the Workspace to reach the Target and if you
> are trying to execute Unit Tests, you'll need to add an explicit Scheme for
> the unit test targets. Here's the configuration from the @RestKithttps://github.com/RestKitunit tests Rakefile:
> 
> namespace :test do
>   task :kill_simulator do
>     system(%q{killall -m -KILL "iPhone Simulator"})
>   end
> 
>   namespace :logic do
>     desc "Run the logic tests for iOS"
>     task :ios => :kill_simulator do
>       config = Xcode.workspace(:RestKit).scheme(:RestKitTests)
>       builder = config.builder
>       build_dir = File.dirname(config.parent.workspace_root) + '/Build'
>       builder.symroot = build_dir + '/Products'
>       builder.objroot = build_dir
>         builder.test(:sdk => 'iphonesimulator')
>     end
> 
> ```
> desc "Run the logic tests for OS X"
> task :osx do
>   config = Xcode.workspace(:RestKit).scheme(:RestKitFrameworkTests)
>   builder = config.builder
>   build_dir = File.dirname(config.parent.workspace_root) + '/Build'
>   builder.symroot = build_dir + '/Products'
>   builder.objroot = build_dir
>     builder.test(:sdk => 'macosx')
> end
> ```
> 
>   end
> 
>   desc "Run the unit tests for iOS and OS X"
>   task :logic => ['logic:ios', 'logic:osx']end
> 
> Hope this helps.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rayh/xcoder/issues/51#issuecomment-12798752.

## 

## 

Yosi Taguri | Co-Founder | Labgoo | iPhone: http://ahhhpah.com | twitter:
http://twitter.com/yosit | Mobile: +972-54-4816020 | Google Voice US
Mobile: +1 (415) 935-1126 | Email: yosi@taguri.com

_Confidential_

**Comment by blakewatters** [comment]
No idea just by looking at the script. I am only leveraging Xcoder for executing my unit tests from the CLI, so I'm not sure what else I can offer beyond the script I've already posted.

**Comment by rayh** [comment]
Hi, sorry, meant to reply to this a while back.

I've seen this before when your Xcode is setup to build derived data to a different location than than Xcode's default.  Xcoder sets the OBJROOT and SYMROOT to be ./build, and I wonder if this messes with it's head.

Can you post the entire console output as a gist and link it here?

**Comment by yosit** [comment]
Thanks for the help.
the script: https://gist.github.com/yosit/de7e7488bb73f7e4e5ac
the log: https://gist.github.com/yosit/d015734bcc5fab746054

On Tue, Feb 12, 2013 at 5:27 AM, Ray Yamamoto Hilton <
notifications@github.com> wrote:

> Hi, sorry, meant to reply to this a while back.
> 
> I've seen this before when your Xcode is setup to build derived data to a
> different location than than Xcode's default. Xcoder sets the OBJROOT and
> SYMROOT to be ./build, and I wonder if this messes with it's head.
> 
> Can you post the entire console output as a gist and link it here?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rayh/xcoder/issues/51#issuecomment-13416564.

## 

## 

Yosi Taguri | Co-Founder | Labgoo | iPhone: http://ahhhpah.com | twitter:
http://twitter.com/yosit | Mobile: +972-54-4816020 | Google Voice US
Mobile: +1 (415) 935-1126 | Email: yosi@taguri.com

_Confidential_

**Comment by yosit** [comment]
Correction, here is the script:
https://gist.github.com/yosit/81ee27f0f3aeee7f2f07

On Tue, Feb 12, 2013 at 10:09 PM, Yosi Taguri yosi@taguri.com wrote:

> Thanks for the help.
> the script: https://gist.github.com/yosit/de7e7488bb73f7e4e5ac
> the log: https://gist.github.com/yosit/d015734bcc5fab746054
> 
> On Tue, Feb 12, 2013 at 5:27 AM, Ray Yamamoto Hilton <
> notifications@github.com> wrote:
> 
> > Hi, sorry, meant to reply to this a while back.
> > 
> > I've seen this before when your Xcode is setup to build derived data to a
> > different location than than Xcode's default. Xcoder sets the OBJROOT and
> > SYMROOT to be ./build, and I wonder if this messes with it's head.
> > 
> > Can you post the entire console output as a gist and link it here?
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/rayh/xcoder/issues/51#issuecomment-13416564.
> 
> ## 
> 
> ## 
> 
> Yosi Taguri | Co-Founder | Labgoo | iPhone: http://ahhhpah.com | twitter:
> http://twitter.com/yosit | Mobile: +972-54-4816020 | Google Voice US
> Mobile: +1 (415) 935-1126 | Email: yosi@taguri.com
> 
> _Confidential_

## 

## 

Yosi Taguri | Co-Founder | Labgoo | iPhone: http://ahhhpah.com | twitter:
http://twitter.com/yosit | Mobile: +972-54-4816020 | Google Voice US
Mobile: +1 (415) 935-1126 | Email: yosi@taguri.com

_Confidential_

**Comment by rayh** [comment]
What happens if you call builder.build without specifying the sdk?  It looks like the scheme is set up to build for x86, but it's trying to build for ARM.  Could you double check how your scheme is set up?  Is this a project or workspace scheme?

**Comment by xslim** [comment]
I managed get it building together like this:

``` ruby
task :test do
  workspace_file = File.basename(Dir.glob('*.xcworkspace').first, '.xcworkspace')
  workspace = Xcode.workspace(workspace_file)

  build_dir = File.join(workspace.workspace_root, 'Build')

  pod_scheme = workspace.schemes.select {|s| s.name == 'Pods'}.first
  if pod_scheme
    puts "Building Pods!!!"
    builder = pod_scheme.builder
    builder.symroot = build_dir + '/Products'
    builder.objroot = build_dir
    builder.build(:sdk => 'iphonesimulator')
  end

  scheme = workspace.schemes.select {|s| s.name != 'Pods'}.first
  puts "Building #{workspace_file}/#{scheme.name}"
  builder = scheme.builder

  builder.target.config('Debug').set 'ONLY_ACTIVE_ARCH', false
  builder.target.project.save!

  builder.symroot = build_dir + '/Products'
  builder.objroot = build_dir
  builder.test(:sdk => 'iphonesimulator')
end
```

**Comment by xslim** [comment]
But now I'm having a strange problem - Tests are failing, but `xcoder` shows `PASSED`

```
  2013-02-27 17:33:31.819 otest[25733:707] *** Assertion failure in +[RKTestFixture setFixtureBundle:], /Users/slim/src/RKInjective/Pods/RestKit/Code/Testing/RKTestFixture.m:36
  2013-02-27 17:33:31.820 otest[25733:707] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Bundle for fixture cannot be nil.'

End tests (PASSED).  Took 0s
```

But maybe it's a different issue to create...

**Comment by rayh** [comment]
I think this is because the process doesnt exit with a non-zero exit code,
but it might be worth running the xcode command line (should be output
before all your test code, prefixed with EXECUTE: ) and see what it does
when run directly.

On 28 February 2013 03:37, Taras Kalapun notifications@github.com wrote:

> But now I'm having a strange problem - Tests are failing, but xcodershows
> PASSED
> 
>   2013-02-27 17:33:31.819 otest[25733:707] **\* Assertion failure in +[RKTestFixture setFixtureBundle:], /Users/slim/src/RKInjective/Pods/RestKit/Code/Testing/RKTestFixture.m:36
>   2013-02-27 17:33:31.820 otest[25733:707] **\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Bundle for fixture cannot be nil.'
> 
> End tests (PASSED).  Took 0s
> 
> But maybe it's a different issue to create...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rayh/xcoder/issues/51#issuecomment-14183826
> .

## 

Ray Hilton

## (maker of mobile apps)

a: 13/243 Collins Street, Melbourne VIC 3000
m: 0430 484 708
w: http://rayh.com.au

**Comment by rayh** [comment]
I've updated xcoder to just use Cocoapods build directory conventions (i.e. Build and Build/Products), but I'm not sure how xcode knows to build Pods automatically as there is no explicit dependency.  We could get around this by just blindly building all referenced projects in the xcworkspace, but it feels a bit heavy-handed

**Comment by rayh** [comment]
I think I've got it, it was failing to use the -workspace option when using a scheme found via a workspace (actually, they exist within the project, but when found via a workspace, the schemes parent is now set to the workspace).

This builds everything ok for me, can you guys check using HEAD?

**Comment by rayh** [comment]
This should be fixed in the latest HEAD, I'm successfully running cocoapods projects now in Jenkins CI.

**Comment by yosit** [comment]
Could you please instruct me on how to install xcoder from the latest HEAD?

**Comment by xslim** [comment]
http://stackoverflow.com/questions/2577346/how-to-install-gem-from-github-source

Check about specific_install gem

**Comment by yosit** [comment]
Thanks,
for the lazy future reader:

gem build GEMNAME.gemspec
gem install gemname-version.gem

**Comment by rayh** [comment]
If you're using bundler, just change your gem 'xcoder' line to:

gem 'xcoder', :git => 'https://github.com/rayh/xcoder.git'

On 17 March 2013 18:51, Yosi Taguri notifications@github.com wrote:

> Thanks,
> for the lazy future reader:
> 
> gem build GEMNAME.gemspec
> gem install gemname-version.gem
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rayh/xcoder/issues/51#issuecomment-15018902
> .

## 

Ray Hilton

## (maker of mobile apps)

a: 13/243 Collins Street, Melbourne VIC 3000
m: 0430 484 708
w: http://rayh.com.au

**Comment by yosit** [comment]
btw, I still get
The following build commands failed:
Check dependencies

can you post a recommended build script for a workspace with cocopods?

On Mon, Mar 18, 2013 at 1:01 AM, Ray Yamamoto Hilton <
notifications@github.com> wrote:

> If you're using bundler, just change your gem 'xcoder' line to:
> 
> gem 'xcoder', :git => 'https://github.com/rayh/xcoder.git'
> 
> On 17 March 2013 18:51, Yosi Taguri notifications@github.com wrote:
> 
> > Thanks,
> > for the lazy future reader:
> > 
> > gem build GEMNAME.gemspec
> > gem install gemname-version.gem
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/rayh/xcoder/issues/51#issuecomment-15018902>
> > .
> 
> ## 
> 
> Ray Hilton
> 
> ## (maker of mobile apps)
> 
> a: 13/243 Collins Street, Melbourne VIC 3000
> m: 0430 484 708
> w: http://rayh.com.au
> 
> —
> 
> Reply to this email directly or view it on GitHubhttps://github.com/rayh/xcoder/issues/51#issuecomment-15033050
> .

## 

## 

Yosi Taguri | Co-Founder | Labgoo | iPhone: http://ahhhpah.com | twitter:
http://twitter.com/yosit | Mobile: +972-54-4816020 | Google Voice US
Mobile: +1 (415) 935-1126 | Email: yosi@taguri.com

_Confidential_

**Comment by rayh** [comment]
In the latest xcoder, there is a command line for invoking projects that
have a Buildspec file, take a look at the README.  Its not final, but it
does simplify the build process in most situations.

Otherwise, you just want to have your rakefile, or whatever, call `pod
setup && pod install` after clean and before build

On 18 March 2013 19:30, Yosi Taguri notifications@github.com wrote:

> btw, I still get
> The following build commands failed:
> Check dependencies
> 
> can you post a recommended build script for a workspace with cocopods?
> 
> On Mon, Mar 18, 2013 at 1:01 AM, Ray Yamamoto Hilton <
> notifications@github.com> wrote:
> 
> > If you're using bundler, just change your gem 'xcoder' line to:
> > 
> > gem 'xcoder', :git => 'https://github.com/rayh/xcoder.git'
> > 
> > On 17 March 2013 18:51, Yosi Taguri notifications@github.com wrote:
> > 
> > > Thanks,
> > > for the lazy future reader:
> > > 
> > > gem build GEMNAME.gemspec
> > > gem install gemname-version.gem
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/rayh/xcoder/issues/51#issuecomment-15018902>
> > > .
> > 
> > ## 
> > 
> > Ray Hilton
> > 
> > ## (maker of mobile apps)
> > 
> > a: 13/243 Collins Street, Melbourne VIC 3000
> > m: 0430 484 708
> > w: http://rayh.com.au
> > 
> > —
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/rayh/xcoder/issues/51#issuecomment-15033050>
> > .
> 
> ## 
> 
> ## 
> 
> Yosi Taguri | Co-Founder | Labgoo | iPhone: http://ahhhpah.com | twitter:
> http://twitter.com/yosit | Mobile: +972-54-4816020 | Google Voice US
> Mobile: +1 (415) 935-1126 | Email: yosi@taguri.com
> 
> _Confidential_
> 
> —
> 
> Reply to this email directly or view it on GitHubhttps://github.com/rayh/xcoder/issues/51#issuecomment-15043561
> .

## 

Ray Hilton

## (maker of mobile apps)

13/243 Collins St, Melbourne VIC 3000  |  +61 (0) 430 484 708  |
http://ray.sh

**Comment by ahsandar** [comment]
I am trying to build using cocoapods, to get builder through scheme I am doing 

Xcode.workspace(''test.xcworkspace'').scheme('Test').builder

but in return I get No such target PFK, available targets are ............
don't know where and how it looks for PFK
I can get the project using workspace but that is of no use as that executes xcodebuild project command instead of workspace, I looked in to workspace.rb scheme method as well, seems that it isn't going there as the exception is saying target instead of scheme, I installed the gem from the HEAD using the command mentioned above
