### ISSUE TITLE
provisioning_profile.rb shell command does not escape string properly

### ISSUE THREAD

**Issue by mgerlach-klick** [rayh/xcoder#73]
provisioning_profile.rb line 57 needs to be changed from `Xcode::Shell.execute("cp #{self.path} #{self.install_path}")` to `Xcode::Shell.execute("cp \"#{self.path}\" #{self.install_path}")` or something similar, or it won't be able to handle a path with (e.g.) white spaces in it

**Comment by mgerlach-klick** [comment]
This is still an issue with 0.1.18. Here the fix is to change provisioning_profile.rb, line 78 from
`cmd <<self.path` to `cmd << "\""+self.path+"\"`

**Comment by rayh** [comment]
Can you submit this as a pull request?  and maybe add a simple spec to
assert it?

On 30 July 2013 06:46, Maximilian Gerlach notifications@github.com wrote:

> This is still an issue with 0.1.18. Here the fix is to change
> provisioning_profile.rb, line 78 from
> cmd << "\""+self.path+"\"" to cmd << "\""+self.path+"\"
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rayh/xcoder/issues/73#issuecomment-21750167
> .

## 

Ray Hilton

## (maker of mobile apps)

13/243 Collins St, Melbourne VIC 3000  |  +61 (0) 430 484 708  |
http://ray.sh

**Comment by rayh** [comment]
Fixed in de71c21
