### ISSUE TITLE
Change the configuration before building

### ISSUE THREAD

**Issue by Noroxs** [rayh/xcoder#93]
Hello everyone.

I know that this project is not supported anymore but maybe someone can help me.

I want to change the TARGETED_DEVICE_FAMILY before building a version. I found the property to change the value but when I build the version the targeted devices are not changed.

What I'm doing wrong? 
Thank you for your help.

Example:

config = Xcode.project('MyProject.xcodeproj').target('Application').config('Debug')
config.targeted_device_family = :ipad
builder = config.builder
builder.build

**Comment by orkoden** [comment]
If I remember correctly you have to save the modified Xcode project file. Can't test it atm though. 

```
project = Xcode.project('MyProject.xcodeproj')
project.save!
```

**Comment by Noroxs** [comment]
project.save! did it for me.

Thank you for the fast answer.
